language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
script:
- cd third-party/poco-1.7.7
- ./configure --static --omit=Data/ODBC,Data/MySQL,Data/PostgreSQL && make -s -j2 && sudo make install
- cd ../../
- mkdir build
- cd build
- cmake ..
- make -j4
branches:
  only:
  - master
notifications:
  email: 191980@niuitmo.ru
env:
  global:
  - LANG="en_US.UTF-8"
