language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
script:
- cd third-party/poco-1.7.7
- ./configure --static --omit=Data/ODBC,Data/MySQL,Data/PostgreSQL && make -s -j2 && sudo make install
- cd ../flatbuffers
- mkdir build
- cd build
- cmake -G "Unix Makefiles" ..
- make
- sudo make install
- cd ../../../
- mkdir build
- cd build
- cmake ..
- make -j4
branches:
  only:
  - master
notifications:
  slack: 0xdeadc0de:UbFdkI7oDi0RkuMZFTQXil9u
env:
  global:
  - LANG="en_US.UTF-8"
